// lib/ui-react/src/lib/components/bmb-card/bmb-card.tsx
import {
  getCardClasses,
  getCardStyles,
  getPaddingClasses,
  getPaddingStyles,
  type IBmbBgColor,
  type IBmbBoxShadowStyle,
  type IBmbCardType,
} from '../../_core/logic/components/card/card';
import { type SizeNames } from '../../_core/types';
import { type CSSProperties, type ReactNode } from 'react';
import './bmb-card.scss';

const toReactStyles = (styles: Record<string, string>): CSSProperties => {
  return Object.fromEntries(
    Object.entries(styles).map(([key, value]) => [
      key.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase()),
      value,
    ]),
  ) as CSSProperties;
};

export interface BmbCardProps {
  borderRadius?: SizeNames | SizeNames[];
  margin?: SizeNames | SizeNames[];
  type?: IBmbCardType;
  state?: 'disabled' | 'error' | 'normal';
  boxShadowStyle?: IBmbBoxShadowStyle | 'none';
  borderColor?: IBmbBgColor | 'default';
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

export interface BmbCardSectionProps {
  padding?: SizeNames | SizeNames[];
  colorBackground?: IBmbBgColor | null;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

export interface BmbCardContentProps extends BmbCardSectionProps {
  setBorderRadius?: boolean;
}

export function BmbCard({
  borderRadius = 'm',
  margin = 'm',
  type = 'normal',
  state = 'normal',
  boxShadowStyle = 'none',
  borderColor = 'default',
  className = '',
  style,
  children,
}: BmbCardProps) {
  const sectionClasses = [
    'bmb_card',
    ...getCardClasses({
      borderRadius,
      margin,
      type,
      boxShadowStyle,
    }),
    state !== 'normal' ? `bmb_card-state-${state}` : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getCardStyles({
        borderRadius,
        margin,
        borderColor,
      }),
    ),
    ...style,
  };

  return (
    <section className={sectionClasses} style={computedStyles}>
      {children}
    </section>
  );
}

export function BmbCardHeader({
  padding = 'm',
  colorBackground = null,
  className = '',
  style,
  children,
}: BmbCardSectionProps) {
  const headerClasses = ['bmb_card-header', ...getPaddingClasses(padding), className]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getPaddingStyles({
        padding,
        colorBackground,
      }),
    ),
    ...style,
  };

  return (
    <header className={headerClasses} style={computedStyles}>
      {children}
    </header>
  );
}

export function BmbCardFooter({
  padding = 'm',
  colorBackground = null,
  className = '',
  style,
  children,
}: BmbCardSectionProps) {
  const footerClasses = ['bmb_card-footer', ...getPaddingClasses(padding), className]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getPaddingStyles({
        padding,
        colorBackground,
      }),
    ),
    ...style,
  };

  return (
    <footer className={footerClasses} style={computedStyles}>
      {children}
    </footer>
  );
}

export function BmbCardContent({
  padding = 'm',
  colorBackground = null,
  setBorderRadius = false,
  className = '',
  style,
  children,
}: BmbCardContentProps) {
  const contentClasses = [
    'bmb_card-content',
    ...getPaddingClasses(padding),
    setBorderRadius ? 'bmb_card-content-with-radius' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getPaddingStyles({
        padding,
        colorBackground,
      }),
    ),
    ...style,
  };

  return (
    <section className={contentClasses} style={computedStyles}>
      {children}
    </section>
  );
}

export default BmbCard;

// ui-angular/src/lib/components/old/bmb-card/bmb-card.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { SizeNames } from '../../types';

const calculateSize = (pixels: string[]): string => {
  return pixels.map((size) => `var(--bmb-radius-${size})`).join(' ');
};

export type IBmbCardType =
  | 'primary'
  | 'secondary'
  | 'succes'
  | 'info'
  | 'warning'
  | 'error'
  | 'normal'
  | 'transparent';

export type IBmbBgColor =
  | 'contrasts-100'
  | 'contrasts-75'
  | 'contrasts-50'
  | 'contrasts-25'
  | 'contrasts-20'
  | 'contrasts-15'
  | 'contrasts-5';

export type IBmbBoxShadowStyle =
  | 'box-shadow-1'
  | 'box-shadow-2'
  | 'box-shadow-3'
  | 'box-shadow-4'
  | 'box-shadow-5'
  | 'box-shadow-6';

@Component({
  selector: 'bmb-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card.component.html',
  styleUrl: './bmb-card.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardComponent {
  borderRadius = input<SizeNames | SizeNames[]>('m');
  margin = input<SizeNames | SizeNames[]>('m');
  type = input<IBmbCardType>('normal');
  state = input<'disabled' | 'error' | 'normal'>('normal');
  boxShadowStyle = input<IBmbBoxShadowStyle | 'none'>('none');
  borderColor = input<IBmbBgColor | 'default'>('default');

  getClasses() {
    const classNames = [];
    if (typeof this.borderRadius() === 'string')
      classNames.push(`bmb_radius-${this.borderRadius()}`);
    if (typeof this.margin() === 'string')
      classNames.push(`bmb_margin-${this.margin()}`);
    classNames.push(`bmb_card-type-${this.type()}`);

    if (this.boxShadowStyle() !== 'none') {
      classNames.push(`bmb_card-${this.boxShadowStyle()}`);
    }

    return classNames;
  }

  getStyles() {
    const styles: any = {};
    if (typeof this.borderRadius() !== 'string')
      styles['border-radius'] = calculateSize(this.borderRadius() as string[]);
    if (typeof this.margin() !== 'string')
      styles.margin = calculateSize(this.margin() as string[]);
    if (this.borderColor() !== 'default')
      styles.borderColor = `var(--general_${this.borderColor()})`;

    return styles;
  }
}

@Component({
  selector: 'bmb-card-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardHeaderComponent {
  padding = input<SizeNames | SizeNames[]>('m');
  colorBackground = input<IBmbBgColor | null>(null);

  getClasses() {
    const classNames = [];
    if (typeof this.padding() === 'string')
      classNames.push(`bmb_padding-${this.padding()}`);

    return classNames;
  }

  getStyles() {
    const styles: any = {};
    if (typeof this.padding() !== 'string')
      styles['padding'] = calculateSize(this.padding() as string[]);

    if (this.colorBackground() !== null) {
      styles['background-color'] = `var(--general_${this.colorBackground()})`;
    }

    return styles;
  }
}

@Component({
  selector: 'bmb-card-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card-footer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardFooterComponent {
  padding = input<SizeNames | SizeNames[]>('m');
  colorBackground = input<IBmbBgColor | null>(null);

  getClasses() {
    const classNames = [];
    if (typeof this.padding() === 'string')
      classNames.push(`bmb_padding-${this.padding()}`);

    return classNames;
  }

  getStyles() {
    const styles: any = {};
    if (typeof this.padding() !== 'string')
      styles['padding'] = calculateSize(this.padding() as string[]);

    if (this.colorBackground() !== null) {
      styles['background-color'] = `var(--general_${this.colorBackground()})`;
    }

    return styles;
  }
}

@Component({
  selector: 'bmb-card-content',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card-content.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardContentComponent {
  padding = input<SizeNames | SizeNames[]>('m');
  colorBackground = input<IBmbBgColor | null>(null);
  setBorderRadius = input<boolean>(false);

  getClasses() {
    const classNames = [];
    if (typeof this.padding() === 'string')
      classNames.push(`bmb_padding-${this.padding()}`);
    if (this.setBorderRadius()) classNames.push('bmb_card-content-with-radius');

    return classNames;
  }

  getStyles() {
    const styles: any = {};
    if (typeof this.padding() !== 'string')
      styles['padding'] = calculateSize(this.padding() as string[]);

    if (this.colorBackground() !== null) {
      styles['background-color'] = `var(--general_${this.colorBackground()})`;
    }
    return styles;
  }
}
