// lib/ui-react/src/lib/components/bmb-badge/bmb-badge.tsx
import {
  getBadgeClasses,
  getBadgeBulletColor,
  type IBmbBadgeAppearanceColors,
} from '../../_core/logic/components/badge/badge';
import { type ReactNode } from 'react';
import './bmb-badge.scss';

export interface BmbBadgeProps {
  appearance?: IBmbBadgeAppearanceColors;
  text?: string;
  container?: boolean;
  className?: string;
  children?: ReactNode;
}

export function BmbBadge({
  appearance = 'normal',
  text = '',
  container = true,
  className = '',
  children,
}: BmbBadgeProps) {
  const sectionClasses = [
    ...getBadgeClasses({
      container,
      appearance,
    }),
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const bulletClasses = ['bmb_badge-bullet', !container ? getBadgeBulletColor(appearance) : '']
    .filter(Boolean)
    .join(' ');

  const content = children ?? text;

  return (
    <section className={sectionClasses}>
      <span className={bulletClasses} />
      <span className="bmb_badge-content">{content}</span>
    </section>
  );
}

export default BmbBadge;

// lib/ui-angular/src/lib/components/bmb-badge/bmb-badge.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ViewEncapsulation,
  input,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  getBadgeClasses,
  getBadgeBulletColor,
  type IBmbBadgeAppearanceColors,
} from '../../_core/logic/components/badge/badge';

@Component({
  selector: 'bmb-badge',
  styleUrl: './bmb-badge.component.scss',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-badge.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbBadgeComponent {
  appearance = input<IBmbBadgeAppearanceColors>('normal');
  text = input<string>('');
  container = input<boolean>(true);

  getClasses(): string[] {
    return getBadgeClasses({
      container: this.container(),
      appearance: this.appearance(),
    });
  }

  getBulletColor(): string {
    return getBadgeBulletColor(this.appearance());
  }
}
