// lib/ui-react/src/lib/components/bmb-card/bmb-card.tsx
import {
  getCardClasses,
  getCardStyles,
  getPaddingClasses,
  getPaddingStyles,
  type IBmbBgColor,
  type IBmbBoxShadowStyle,
  type IBmbCardType,
} from '../../_core/logic/components/card/card';
import { type SizeNames } from '../../_core/types';
import { type CSSProperties, type ReactNode } from 'react';
import './bmb-card.scss';

const toReactStyles = (styles: Record<string, string>): CSSProperties => {
  return Object.fromEntries(
    Object.entries(styles).map(([key, value]) => [
      key.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase()),
      value,
    ]),
  ) as CSSProperties;
};

export interface BmbCardProps {
  borderRadius?: SizeNames | SizeNames[];
  margin?: SizeNames | SizeNames[];
  type?: IBmbCardType;
  state?: 'disabled' | 'error' | 'normal';
  boxShadowStyle?: IBmbBoxShadowStyle | 'none';
  borderColor?: IBmbBgColor | 'default';
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

export interface BmbCardSectionProps {
  padding?: SizeNames | SizeNames[];
  colorBackground?: IBmbBgColor | null;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

export interface BmbCardContentProps extends BmbCardSectionProps {
  setBorderRadius?: boolean;
}

export function BmbCard({
  borderRadius = 'm',
  margin = 'm',
  type = 'normal',
  state = 'normal',
  boxShadowStyle = 'none',
  borderColor = 'default',
  className = '',
  style,
  children,
}: BmbCardProps) {
  const sectionClasses = [
    'bmb_card',
    ...getCardClasses({
      borderRadius,
      margin,
      type,
      boxShadowStyle,
    }),
    state !== 'normal' ? `bmb_card-state-${state}` : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getCardStyles({
        borderRadius,
        margin,
        borderColor,
      }),
    ),
    ...style,
  };

  return (
    <section className={sectionClasses} style={computedStyles}>
      {children}
    </section>
  );
}

export function BmbCardHeader({
  padding = 'm',
  colorBackground = null,
  className = '',
  style,
  children,
}: BmbCardSectionProps) {
  const headerClasses = ['bmb_card-header', ...getPaddingClasses(padding), className]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getPaddingStyles({
        padding,
        colorBackground,
      }),
    ),
    ...style,
  };

  return (
    <header className={headerClasses} style={computedStyles}>
      {children}
    </header>
  );
}

export function BmbCardFooter({
  padding = 'm',
  colorBackground = null,
  className = '',
  style,
  children,
}: BmbCardSectionProps) {
  const footerClasses = ['bmb_card-footer', ...getPaddingClasses(padding), className]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getPaddingStyles({
        padding,
        colorBackground,
      }),
    ),
    ...style,
  };

  return (
    <footer className={footerClasses} style={computedStyles}>
      {children}
    </footer>
  );
}

export function BmbCardContent({
  padding = 'm',
  colorBackground = null,
  setBorderRadius = false,
  className = '',
  style,
  children,
}: BmbCardContentProps) {
  const contentClasses = [
    'bmb_card-content',
    ...getPaddingClasses(padding),
    setBorderRadius ? 'bmb_card-content-with-radius' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const computedStyles = {
    ...toReactStyles(
      getPaddingStyles({
        padding,
        colorBackground,
      }),
    ),
    ...style,
  };

  return (
    <section className={contentClasses} style={computedStyles}>
      {children}
    </section>
  );
}

export default BmbCard;

// lib/ui-angular/src/lib/components/bmb-card/bmb-card.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  input,
  ViewEncapsulation,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { SizeNames } from '../../types';
import {
  getCardClasses,
  getCardStyles,
  getPaddingClasses,
  getPaddingStyles,
  type IBmbBgColor,
  type IBmbBoxShadowStyle,
  type IBmbCardType,
} from '../../_core/logic/components/card/card';



@Component({
  selector: 'bmb-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card.component.html',
  styleUrl: './bmb-card.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardComponent {
  borderRadius = input<SizeNames | SizeNames[]>('m');
  margin = input<SizeNames | SizeNames[]>('m');
  type = input<IBmbCardType>('normal');
  state = input<'disabled' | 'error' | 'normal'>('normal');
  boxShadowStyle = input<IBmbBoxShadowStyle | 'none'>('none');
  borderColor = input<IBmbBgColor | 'default'>('default');

  getClasses(): string[] {
    return getCardClasses({
      borderRadius: this.borderRadius(),
      margin: this.margin(),
      type: this.type(),
      boxShadowStyle: this.boxShadowStyle(),
    });
  }

  getStyles(): Record<string, string> {
    return getCardStyles({
      borderRadius: this.borderRadius(),
      margin: this.margin(),
      borderColor: this.borderColor(),
    });
  }
}

@Component({
  selector: 'bmb-card-header',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card-header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardHeaderComponent {
  padding = input<SizeNames | SizeNames[]>('m');
  colorBackground = input<IBmbBgColor | null>(null);

  getClasses(): string[] {
    return getPaddingClasses(this.padding());
  }

  getStyles(): Record<string, string> {
    return getPaddingStyles({
      padding: this.padding(),
      colorBackground: this.colorBackground(),
    });
  }
}

@Component({
  selector: 'bmb-card-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card-footer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardFooterComponent {
  padding = input<SizeNames | SizeNames[]>('m');
  colorBackground = input<IBmbBgColor | null>(null);

  getClasses(): string[] {
    return getPaddingClasses(this.padding());
  }

  getStyles(): Record<string, string> {
    return getPaddingStyles({
      padding: this.padding(),
      colorBackground: this.colorBackground(),
    });
  }
}

@Component({
  selector: 'bmb-card-content',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-card-content.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbCardContentComponent {
  padding = input<SizeNames | SizeNames[]>('m');
  colorBackground = input<IBmbBgColor | null>(null);
  setBorderRadius = input<boolean>(false);

  getClasses(): string[] {
    const classes = getPaddingClasses(this.padding());

    if (this.setBorderRadius()) {
      classes.push('bmb_card-content-with-radius');
    }

    return classes;
  }

  getStyles(): Record<string, string> {
    return getPaddingStyles({
      padding: this.padding(),
      colorBackground: this.colorBackground(),
    });
  }
}
