// ui-angular/src/lib/components/bmb-badge/bmb-badge.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  ViewEncapsulation,
  input,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  getBadgeBulletClass,
  getBadgeClasses,
} from '../../_shared/logic/components/badge';
import { IBmbBadgeAppearance } from '../../_shared/types/components/badge';

@Component({
  selector: 'bmb-badge',
  styleUrl: './bmb-badge.component.scss',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './bmb-badge.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class BmbBadgeComponent {
  appearance = input<IBmbBadgeAppearance>('normal');
  text = input<string>('');
  container = input<boolean>(true);

  getClasses(): string[] {
    return getBadgeClasses(this.appearance(), this.container());
  }

  getBulletColor(): string {
    return getBadgeBulletClass(this.appearance());
  }
}

<section [ngClass]="getClasses()">
  <span
    class="bmb_badge-bullet"
    [ngClass]="!container() ? getBulletColor() : ''"
  ></span>
  <span class="bmb_badge-content"> {{ text() }} </span>
</section>

// ui-react/src/lib/component/bmb-badge/index.tsx
import {
  getBadgeBulletClass,
  getBadgeClasses,
} from '../../_shared/logic/components/badge';
import { IBmbBadgeAppearance } from '../../_shared/types';

export interface BmbBadgeProps {
  appearance?: IBmbBadgeAppearance;
  text: string;
  container: boolean;
}

export const BmbBadge = ({
  appearance = 'normal',
  text = '',
  container = true,
}) => {
  const getClasses = (): string => {
    return getBadgeClasses(appearance, container).join(' ');
  }

  const getBulletColor = (): string => {
    return getBadgeBulletClass(appearance);
  }

  return (
    <section className={getClasses()} >
      <span
        className={getBulletColor()}
      ></span>
      <span className="bmb_badge-content"> { text } </span>
    </section>
  )
}
